dataset:
  annotations: /home/souramandal/perceptron-posse-COMP9444/hagrid/annotations_test1/
  dataset: /home/souramandal/perceptron-posse-COMP9444/hagrid/subsamples_test1/
  targets:
    - call
    - dislike
    - fist
    - like
    - mute
    - ok
    - peace
    - stop
    - stop_inverted
    - peace_inverted
    - no_gesture
  image_size: [224, 224]
  subset: 2000
random_state: 42
device: 'cuda'
experiment_name: perceptron-posse-grayscaled-resnet20-testing
model:
  name: 'ResNet20'  # 'ResNet18' or 'ResNet10' or 'ResNet20'
  pretrained: False
  freezed: False
  start_epoch: 0
  checkpoint: /home/souramandal/perceptron-posse-COMP9444/hagrid/classifier/experiments/perceptron-posse-grayscaled-resnet20/best_model.pth # change checkpoint for testing run
optimizer:
  lr: 0.005
  momentum: 0.9
  weight_decay: 0.0005
scheduler:
  start_factor: 0.001
train_params:
  epochs: 75
  num_workers: 12
  train_batch_size: 64
  test_batch_size: 20
  prefetch_factor: 16
metric_params:
  metrics: ['accuracy', 'f1_score', 'precision', 'recall']
  average: 'weighted'
