dataset:
  annotations: /home/souramandal/perceptron-posse-COMP9444/hagrid/annotations_train
  dataset: /home/souramandal/perceptron-posse-COMP9444/hagrid/subsamples_train/
  targets:
    - call
    - dislike
    - fist
    - like
    - mute
    - ok
    - peace
    - stop
    - stop_inverted
    - peace_inverted
    - no_gesture
  image_size: [224, 224]
  subset: 2000
random_state: 42
device: 'cuda'
experiment_name: perceptron-posse
model:
  name: 'ResNet18'  # 'MobileNetV3_large' or 'MobileNetV3_small' or 'ResNet18'
  pretrained: False
  freezed: False
  start_epoch: 0
  checkpoint: /path/to/chackpoint
optimizer:
  lr: 0.005
  momentum: 0.9
  weight_decay: 0.0005
scheduler:
  start_factor: 0.001
train_params:
  epochs: 5
  num_workers: 16
  train_batch_size: 64
  test_batch_size: 64
  prefetch_factor: 16
metric_params:
  metrics: ['accuracy', 'f1_score', 'precision', 'recall']
  average: 'weighted'
